server:
  port: ${PORT:8200}
spring:
  application:
    name: address-api
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
