server:
  port: ${PORT:8400}
spring:
  application:
    name: course-api
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

